name: "Spring Boot Deploy"
description: "Deploy Spring Boot app to EC2"

inputs:
  ec2_host:
    required: true
  ec2_user:
    required: true
  ec2_key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run deploy script
      shell: bash
      run: |
        echo "${{ inputs.ec2_key }}" | base64 -d > ec2-key.pem
        chmod 600 ec2-key.pem
        bash $GITHUB_ACTION_PATH/deploy.sh \
          "${{ inputs.ec2_host }}" \
          "${{ inputs.ec2_user }}" \
          "ec2-key.pem"
