name: "Spring Boot Deploy to EC2"
description: "Deploy Spring Boot application to EC2 using SSH and SCP"
author: "Your Name"
runs:
  using: "composite"
  steps:
    - name: Make deploy.sh executable
      run: chmod +x $GITHUB_ACTION_PATH/deploy.sh
      shell: bash

    - name: Run deploy script
      run: $GITHUB_ACTION_PATH/deploy.sh
      shell: bash
      env:
        EC2_SSH_KEY: ${{ inputs.EC2_SSH_KEY }}
        EC2_USER: ${{ inputs.EC2_USER }}
        EC2_HOST: ${{ inputs.EC2_HOST }}

inputs:
  EC2_SSH_KEY:
    description: "Base64 encoded EC2 private key"
    required: true
  EC2_USER:
    description: "EC2 username (e.g., ubuntu or ec2-user)"
    required: true
  EC2_HOST:
    description: "EC2 public IP or DNS"
    required: true
