name: "Spring Boot Deploy"
description: "Builds and deploys Spring Boot app to EC2"

runs:
  using: "composite"
  steps:
    - name: Run deploy script
      shell: bash
      run: bash $GITHUB_ACTION_PATH/deploy.sh
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
