name: "Spring Boot Deploy"
description: "Deploy Spring Boot JAR to AWS EC2"

inputs:
  ec2_host:
    description: "EC2 public DNS or IP"
    required: true
  ec2_user:
    description: "EC2 username (ec2-user for Amazon Linux, ubuntu for Ubuntu)"
    required: true
  ec2_key:
    description: "EC2 private key (PEM)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run deploy script
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/deploy.sh \
        "${{ inputs.ec2_host }}" \
        "${{ inputs.ec2_user }}" \
        "${{ inputs.ec2_key }}"
