name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: myapp   # 👈 this is important!

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: myapp/target/*.jar  # 👈 correct path

      - name: Deploy to EC2
        uses: ./.github/actions/springboot-deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ec2-user
          key: ${{ secrets.EC2_KEY }}
          jar_path: myapp/target/*.jar
