name: CI/CD Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Build Spring Boot JAR (inside myapp folder)
      - name: Build with Maven
        run: |
          cd myapp
          mvn clean package -DskipTests

      # 4. Deploy to EC2 using custom action
      - name: Deploy Spring Boot App
        uses: ./.github/actions/springboot-deploy
        with:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
