name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main   # Run workflow only on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build Spring Boot App with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests --file myapp/pom.xml

      # Step 4: Upload JAR as artifact (v4)
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: myapp/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download JAR from build job (v4)
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: springboot-jar
          path: .

      # Step 2: Add SSH key
      - name: Setup SSH
        run: |
          echo "$EC2_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 3: Copy JAR to EC2
      - name: Copy JAR to EC2
        run: scp -i ec2-key.pem -o StrictHostKeyChecking=no *.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app.jar

      # Step 4: Run Deploy Script on EC2
      - name: Run Deploy Script
        run: ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "bash ~/deploy.sh"
