name: CI/CD Spring Boot to EC2

on:
  push:
    branches:
      - main   # Trigger only when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Build with Maven (point to myapp directory)
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./myapp

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}   # private key
          EC2_USER: ${{ secrets.EC2_USER }}         # usually ec2-user or ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}         # public IP or DNS
        run: |
           chmod +x .github/actions/springboot-deploy/deploy.sh
           .github/actions/springboot-deploy/deploy.sh
