name: CI/CD Spring Boot to EC2

on:
  push:
    branches:
      - main   # deploy only when pushing to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: ./myapp   # ✅ important fix

    - name: Upload JAR to EC2
      run: |
        echo "$EC2_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem
        scp -o StrictHostKeyChecking=no -i ec2-key.pem ./myapp/target/*.jar ec2-user@$EC2_HOST:/home/ec2-user/app.jar
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@$EC2_HOST "bash ~/deploy.sh"
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
