name: CI/CD Spring Boot App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        working-directory: ./myapp   # update if your pom.xml is elsewhere

      - name: Run Spring Boot Deploy Action
        uses: ./.github/actions/springboot-deploy
        with:
          ec2_host: ${{ secrets.EC2_HOST }}
          ec2_user: ${{ secrets.EC2_USER }}
          ec2_key: ${{ secrets.EC2_KEY }}
