name: Deploy Spring Boot App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./myapp   # 👈 path to your pom.xml

      - name: Deploy to EC2
        uses: ./.github/actions/springboot-deploy
        with:
          ec2_host: ${{ secrets.EC2_HOST }}
          ec2_user: ${{ secrets.EC2_USER }}
          ec2_key: ${{ secrets.EC2_KEY }}
